CREATE TABLE IF NOT EXISTS NxPanicNxPools (
  Id INTEGER PRIMARY KEY,
  Name TEXT NOT NULL,
  Description TEXT
);

CREATE TABLE IF NOT EXISTS NxPanicNxGroups (
  Id INTEGER PRIMARY KEY,
  PoolId INTEGER NOT NULL,
  Message TEXT NOT NULL,
  FOREIGN KEY (PoolId) REFERENCES NxPanicNxPools(Id)
);

