CREATE TABLE IF NOT EXISTS NxInfoNxPools (
  Id INTEGER PRIMARY KEY,
  Name TEXT NOT NULL,
  Description TEXT
);

CREATE TABLE IF NOT EXISTS NxInfoNxGroups (
  Id INTEGER PRIMARY KEY,
  PoolId INTEGER NOT NULL,
  Message TEXT NOT NULL,
  FOREIGN KEY (PoolId) REFERENCES NxInfoNxPools(Id)
);

