CREATE TABLE IF NOT EXISTS NxCriticalNxPools (
  Id INTEGER PRIMARY KEY,
  Name TEXT NOT NULL,
  Description TEXT
);

CREATE TABLE IF NOT EXISTS NxCriticalNxGroups (
  Id INTEGER PRIMARY KEY,
  PoolId INTEGER NOT NULL,
  Message TEXT NOT NULL,
  FOREIGN KEY (PoolId) REFERENCES NxCriticalNxPools(Id)
);

