unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g update-environment "DISPLAY KRB5CCNAME MSYSTEM SSH_AGENT_PID SSH_ASKPASS SSH_AUTH_SOCK SSH_CONNECTION WINDOWID XAUTHORITY PATH NEXUS_CNF"

bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"
bind-key Tab last-window

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

bind-key r source-file "${NEXUS_CNF}/.tmux.conf" \; display-message "tmux config reloaded"

set -g mode-keys vi
set -g status-position top
set -g status-interval 1
set -g status-justify centre
set -g status-left-length 20
set -g status-right-length 140
set -sg escape-time 0
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g mouse off
set -g focus-events on
set -g default-terminal "xterm-256color"
set -as terminal-features ",xterm-256color:RGB"
setw -g aggressive-resize on

set -g status-right '#[bg=#1e1f29,fg=#a3be8c,bold]  '
set -g status-left ''
set -g message-style 'bg=#4c566a fg=#fefefe bold'
set -g status-style 'bg=#30363d fg=#88c0d0 bold'
set -g renumber-windows on

setw -g window-status-format ' #I:#W '
setw -g window-status-current-format '#[bg=#1e1f29,fg=#a3be8c,bold] #I:#W '
set -g pane-border-style 'bg=#30363d fg=#00e68a'
set -g pane-active-border-style 'bg=#ffffff fg=#01e68a'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Plugin settings
set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'


